cc/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('courses/', views.CourseListView.as_view(), name='courses'),
    path('instructors/', views.InstructorListView.as_view(), name='instructors'),
    path('course/<int:pk>', views.CourseDetailView.as_view(), name='course-detail'),
    path('mycourses/', views.registeredCourseByUser.as_view(), name='my-registered'),
    path('course/<uuid:pk>', views.change_data_faculty, name='change-data-faculty'),
    path('cc/sort', views.sort, name='sort'),
]

mysite/urls.py
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]
# Use include() to add paths from the catalog application 
from django.urls import include
from django.urls import path

urlpatterns += [
    path('cc/', include('cc.urls')),
]

from django.views.generic import RedirectView
urlpatterns += [
    path('', RedirectView.as_view(url='/cc/', permanent=True)),
]
# Use static() to add url mapping to serve static files during development (only)
from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += [
    path('cc/', include('cc.urls')),
]
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

cc/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import User
from datetime import date


class Major(models.Model):
    name = models.CharField(max_length=200, help_text='Major (e.g. Computer Science)')
    
    def __str__(self):
        return self.name

from django.urls import reverse # Used to generate URLs by reversing the URL patterns

class Course(models.Model):
    title = models.CharField(max_length=200)

    instructor = models.ForeignKey('Instructor', on_delete=models.SET_NULL, null=True)
    
    summary = models.TextField(max_length=1000, help_text='Enter a brief summary of course')
    major = models.ManyToManyField(Major, help_text='Select a major of this course')
    
    def __str__(self):
        """String for representing the Model object."""
        return self.title
    
    def get_absolute_url(self):
        """Returns url to access course detail."""
        return reverse('course-detail', args=[str(self.id)])

    def showmajor(self):
        return ', '.join(major.name for major in self.major.all()[:3])
    
    showmajor.short_description = 'Major'

import uuid # Required for unique book instances

class CourseInstance(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Course lecture number')
    course = models.ForeignKey('Course', on_delete=models.SET_NULL, null=True) 
    regstudent = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    REG_STATUS = (
        ('c', 'Closed'),
        ('a', 'Available'),
        ('w', 'WaitList')
    )
    next_registration = models.DateField(null=True, blank=True)
    summary = models.CharField(null=True, max_length=200)
    status = models.CharField(
        max_length=1,
        choices=REG_STATUS,
        blank=True,
        default='w',
        help_text='Course availability',
    )

    def __str__(self):
        return f'{self.id} ({self.course.title})'

class Instructor(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)

    class Meta:
        ordering = ['last_name', 'first_name']

    def __str__(self):
        return f'{self.last_name}, {self.first_name}'

cc/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

class ChangeDataForm(forms.Form):
    form_summary = forms.CharField(max_length=200, help_text="Enter technologies", required = False)
    form_next_registration = forms.DateField(help_text="Enter registration date. Past date also can be selected")

class SortForm(forms.Form):
    numbers = forms.CharField(widget=forms.Textarea)
    CHOICES=[('Ascending','Ascending'),('Descending','Descending')]

    like = forms.ChoiceField(choices=CHOICES)
    

cc/views.py
from django.shortcuts import render

# Create your views here.

import datetime
import operator
from django.contrib.auth.decorators import permission_required
from django.shortcuts import get_object_or_404
from django.urls import reverse
from cc.forms import ChangeDataForm
from cc.forms import SortForm
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from cc.models import Course, Instructor, CourseInstance, Major

def sort(request):
    # If this is a POST request then process the Form data
    if request.method == 'POST':

        # Create a form instance and populate it with data from the request (binding):
        form = SortForm(request.POST)
        # Check if the form is valid:
        if form.is_valid():
            numbers = form.cleaned_data['numbers']
            numbers = numbers.replace(",", " ").split()
            order = form.cleaned_data['like']
            try:
            	p = list(map(int, numbers))
            	sortedNumbers = mySort(p, order)
            	error = False
            except:
            	error = True
            	sortedNumbers = "Give Valid Input"

            context = {
		'form': form,
                'numbers': sortedNumbers,
        	'submit': True,
                'error': error
            }
    else:
        form = SortForm()
        context = {
   	    'form': form,
            'submit': False,
        }
    return render(request, 'cc/sort.html', context)

def mySort(numbers,order):
    if len(numbers)>1:
        mid = len(numbers)//2
        lefthalf = numbers[:mid]
        righthalf = numbers[mid:]

        mySort(lefthalf, order)
        mySort(righthalf, order)

        p= 0
        q = 0
        r= 0
        operator = ""
        if(order == "Ascending"):
            while p < len(lefthalf) and q < len(righthalf):
                if lefthalf[p] < righthalf[q]:
                    numbers[r]=lefthalf[p]
                    p=p+1
                else:
                    numbers[r]=righthalf[q]
                    q=q+1
                r=r+1
        else:
            while p < len(lefthalf) and q < len(righthalf):
                if lefthalf[p] > righthalf[q]:
                    numbers[r]=lefthalf[p]
                    p=p+1
                else:
                    numbers[r]=righthalf[q]
                    q=q+1
                r=r+1
        while p < len(lefthalf):
            numbers[r]=lefthalf[p]
            p=p+1
            r=r+1

        while q < len(righthalf):
            numbers[r]=righthalf[q]
            q=q+1
            r=r+1
    return numbers
         

def index(request):
    num_courses = Course.objects.all().count()
    num_lectures = CourseInstance.objects.all().count()
    
    # Available books (status = 'a')
    num_lectures_available = CourseInstance.objects.filter(status__exact='a').count()
    
    # The 'all()' is implied by default.    
    num_instructors = Instructor.objects.count()
    
    context = {
        'num_courses': num_courses,
        'num_lectures': num_lectures,
        'num_lectures_available': num_lectures_available,
        'num_instructors': num_instructors,
    }

    return render(request, 'index.html', context=context)



class CourseListView(generic.ListView):

    model = Course
    context_object_name = 'course'   
    #queryset = Course.objects.filter(title__icontains='')[:3]  
    template_name = 'course.html'  

class InstructorListView(generic.ListView):

    model = Instructor
    context_object_name = 'instructor'   
    template_name = 'instructor.html' 

class CourseDetailView(generic.DetailView):
    model = Course
    template_name = 'coursedetail.html' 

class registeredCourseByUser(LoginRequiredMixin,generic.ListView):
    model = CourseInstance
    template_name ='cc/course_registered'
    
    def get_queryset(self):
        return CourseInstance.objects.filter(regstudent=self.request.user)

def change_data_faculty(request, pk):
    course_instance = get_object_or_404(CourseInstance, pk=pk)
    # If this is a POST request then process the Form data
    if request.method == 'POST':

        # Create a form instance and populate it with data from the request (binding):
        form = ChangeDataForm(request.POST)

        # Check if the form is valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required (here we just write it to the model due_back field)
            course_instance.next_registration =  form.cleaned_data['form_next_registration']
            course_instance.summary = form.cleaned_data['form_summary'] 
            course_instance.save()
            context = {
        	'form': form,
        	'course_instance': course_instance,
        	'submit': True,
                'mydate' : course_instance.next_registration +  datetime.timedelta(days=10)
 
            }

    # If this is a GET (or any other method) create the default form.
    else:
        proposed_form_summary = course_instance.summary
        proposed_form_next_registration = course_instance.next_registration
        form = ChangeDataForm(initial={'form_next_registration': proposed_form_next_registration,'form_summary':proposed_form_summary})
        context = {
        'form': form,
        'course_instance': course_instance,
	'submit':False
        }
    
    return render(request, 'cc/change_data_faculty.html', context)

cc/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}<title>Courses</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
  <div class="container-fluid">
    <div class="row" >
      <div class="col-sm-3">
      {% block sidebar %}
        <ul class="sidebar-nav sidenav">
          <li><a href="{% url 'sort' %}">Sort Numbers</a></li>
          <li><a href="{% url 'index' %}">Home</a></li>
	  <li><a href="{% url 'courses' %}">All courses</a></li>
          <li><a href="{% url 'instructors' %}">Instructors List</a></li>
          {% if user.is_authenticated %}
            <li><h4 style="color:blue;">User: {{ user.get_username }}</h4></li>
	    <li><a href="{% url 'my-registered' %}">My Courses</a></li> 
            <li><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li> 
          {% else %}
    	    <li><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>     
          {% endif %} 
        </ul>
      {% endblock %}
      </div>
      <div class="col-sm-9 rightContent">{% block content %}{% endblock %}</div>
    </div>
  </div>
</body>
</html>

cc/templates/course.html
{% extends "base.html" %}

{% block content %}
  <h1>Course List</h1>
  {% if course %}
  <ul>
    {% for c in course %}
      <li>
        <a href="{{ c.get_absolute_url }}">{{ c.title }}</a> ({{c.instructor}})
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no courses in the available</p>
  {% endif %}       
{% endblock %}

cc/templates/coursedetail.html
{% extends "base.html" %}

{% block content %}
  <h1>Title: {{ course.title }}</h1>

  <p><strong>Instructor:</strong> <a>{{ course.instructor }}</a></p>
  <p><strong>Summary:</strong> {{ course.summary }}</p>
  <p><strong>Major:</strong> {% for major in course.major.all %} {{ major}}{% if not forloop.last %}, {% endif %}{% endfor %}</p>  

  <div style="margin-left:20px;margin-top:20px">
    <h4>Lectures</h4>

    {% for copy in course.courseinstance_set.all %}
      <hr>
      <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'c' %}text-danger{% else %}text-warning{% endif %}">{{ copy.get_status_display }}</p>
      {% if copy.status != 'a' %}
        <p><strong>No availability</strong></p>
      {% endif %}
{% url 'index' %}
      <p><a href="{{copy.id}}" ><strong>Id:</strong> {{copy.id}}</a></p>
    {% endfor %}
  </div>
{% endblock %}

cc/templates/index.html
{% extends "base.html" %}

{% block content %}
  <h1>Course Details</h1>

  <ul>
    <li><strong>Number of</strong> <a href="{% url 'courses' %}"><strong>Courses:</strong> {{ num_courses }}</a></li>
    <li><strong>Total Lectures:</strong> {{ num_lectures }}</li>
    <li><strong>Lectures available:</strong> {{ num_lectures_available }}</li>
    <li><strong>Number of</strong> <a href="{% url 'instructors' %}"><strong>Instructors:</strong> {{ num_instructors}}</a></li>
  </ul>
{% endblock %}

cc/templates/instructor.html
{% extends "base.html" %}

{% block content %}
  <h1>Instructors</h1>
  {% if instructor %}
  <ul>
    {% for c in instructor %}
      <li>
        {{ c.first_name }} {{ c.last_name}} (DOB: {{c.date_of_birth}})
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no courses in the available</p>
  {% endif %}       
{% endblock %}